### ISSUE TITLE
Tiny failure case

### ISSUE THREAD

**Issue by alecjacobson** [qnzhou/trianglelite#1]
Triangle is failing to triangulate the convex hull with these vertices
```
6.899643741648033 10.556739733611963
6.8743893086546723 10.577559204153792
6.8990280198173055 10.557055643048765
6.8994694525740767 10.556817827203695
6.8996252478389311 10.556759464230709
6.899537086138448 10.5566972172105
```
and these constraint edges
``` 
1 2
3 4
4 5
5 4
```

**Comment by qnzhou** [comment]
Just to double check, are the indices starting from 0 in your example?  (I set the `z` flag for triangle implicitly to support 0-based index.)

**Comment by alecjacobson** [comment]
Sorry for the confusion. They start at 1 (vertex 1 is [6.899643741648033 10.556739733611963])

**Comment by alecjacobson** [comment]
This example (and lots others like it) are especially painful because it seems to send triangle into an infinite loop.

**Comment by qnzhou** [comment]
My debug traced to this loop: https://github.com/PyMesh/triangle/blob/afc07fb324307dd485b0873bf355ee791be846cc/triangle.c#L11659-L11673

Basically, triangle is looking for the first triangle on a path.  It is looping through 4 vertices and turns out all 4 vertices are all on the right of the search path.

```
#810: 6.899643741648033  10.556739733611963
#8b0: 6.899537086138448  10.5566972172105  
#8d0: 6.8996152772410877 10.55676319934893   
#890: 6.8996252478389311 10.556759464230709
```
The interesting observation is that point `#8d0` is not from the input, thus is inaccurate.  Not sure how it got created.

**Comment by qnzhou** [comment]
The input segments actually has a tiny intersection.  That explains the extra vertex.  I consider triangle's intersection resolution not robust, however, if preprocessing can resolve these intersections triangle should be pretty good.

![image](https://user-images.githubusercontent.com/3606672/119381198-24e0f580-bc8f-11eb-94c9-7b4ef061f0d5.png)

**Comment by alecjacobson** [comment]
Oh nice! I got to the same place :-) the libigl triangle fork will now at
least throw an except rather than loop forever

**Comment by qnzhou** [comment]
Great!  I probably have to sync up my repo with libigl's triangle.

**Comment by qnzhou** [comment]
Updated to libigl in 8a36714ca3eb40117620792b99327c0aeafd0b62.
